kind: Service
apiVersion: v1
metadata:
  name: lvs-service
  labels:
    lvs: backend
spec:
  type: NodePort
  ports:
  - name: lvs-port
    protocol: TCP    
    port: 3660
    targetPort: 3660
  selector:
    app: lvs