kind: Service
apiVersion: v1
metadata:
  name: lvapi-service
  labels:
    lvapi: backend
spec:
  type: NodePort
  ports:
  - name: lvapi-port
    protocol: TCP    
    port: 30081
    targetPort: 30081
    nodePort: 30081
  selector:
    app: lvapi