apiVersion: v1
kind: Service
metadata:
  name: lvf-service
  labels:
    lvf: frontend 
spec:
  type: NodePort
  ports:
  - name: lvf-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: lvf