apiVersion: apps/v1
kind: Deployment
metadata:
  name: lvf-deployment
  labels:
    lvf: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lvf
  template:
    metadata:
      labels:
        app: lvf
    spec:
      containers:
        - name: lvf
          image: nailyks/logger-viewer-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      # imagePullSecrets:
      #   - name: lvf-key